services:
  postgres:
    image: postgres:15-alpine
    container_name: web-finance-postgres
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web-finance
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: web-finance-app
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/web-finance
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_APP_URL: http://localhost:3002
      NEXTAUTH_URL: http://localhost:3002
      AUTH_TRUST_HOST: "true"
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - postgres
    volumes:
      - uploads:/app/public/uploads
    restart: always

volumes:
  pgdata:
  uploads:
